version: '3'

services:
  redis:
    image: "redis:7.4.2"
    container_name: redis

  django:
    build: .
    container_name: django
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./app:/app  # Mount the app directory to the container
    depends_on:
      - redis
    ports:
      - "8000:8000"

  celery:
    build: .
    container_name: celery
    command: ["celery", "-A", "stock_app", "worker", "--loglevel=info"]
    volumes:
      - ./app:/app  # Mount the app directory to the container
    depends_on:
      - django
      - redis
